# Changes here will be overwritten by Copier
_commit: e0a956f
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2024'
documentation: true
email: nick@koston.org
full_name: J. Nick Koston
github_username: bdraco
has_cli: false
initial_commit: true
open_source_license: Apache Software License 2.0
package_name: aiohttp_isal
project_name: aiohttp-isal
project_short_description: isal support for aiohttp
project_slug: aiohttp-isal
run_poetry_install: true
setup_github: true
setup_pre_commit: true

